### ISSUE TITLE
more units

### ISSUE THREAD

**Issue by erosson** [swarmsim/swarm#13]
create another tree of units, with another currency, for advanced players? we have plenty for first-timers/first reset, more would be confusing but advanced players can handle it.

**Comment by Shoelace** [comment]
maybe this could be lavae based..  ie super lavae, ultra lavae?

or you could get hatchery upgrades..  
or there was the suggestion of units that consume other units.
it would consume territory and meat to produce lavae.. ?

**Comment by erosson** [comment]
this issue was created before energy/mutagen existed (before tabs existed too, I think). adding more units now is a content patch, not a single issue.
