### ISSUE TITLE
nerf mutagen larvae

### ISSUE THREAD

**Issue by erosson** [swarmsim/swarm#317]
too many people getting confused when larva production drops after they spend mutagen.

no unlock required for this, probably.

maybe give production a curve, rather than linear the way it is now - worried about mutagen larva being productive for too long.

**Comment by Shoelace** [comment]
i dont like this idea.. 

clickerheroes has a similar mechanic..  the 'unspent' amount give a bonus.. and you get a different bonus when its spent.

maybe a betetr solution bight be to expand teh details on teh lavae production screen to illustrate where the production is coming from.

ie hatchery, territory and other multiplers and mutagen..

**Comment by DayShine** [comment]
I agree with Shoelace in that it's more of a issue with the lack of representation of income from multiple sources.

For example, I would expect either the Territory tab to show the breakdown in the list of items, or the Territory item itself to show a breakdown. Currently, neither do. The larvae item has the same issue, which is why this is confusing.

"You earn 360,233 larvae per second. (×115 bonus)"

"Larva production increased by 1% per 10 achievement points."

Yet they don't stack, because the Larva item isn't actually Larva but a source of Larva!

**Comment by erosson** [comment]
I agree that mutagen messes up the larvae UI really bad right now. created #354 to fix it - thanks for pointing it out.

still considering rebalancing unspent mutagen/moving their power to a new upgrade, but unlikely to make a final decision on it until the larvae UI sucks less.

**Comment by erosson** [comment]
probably not going to move mutagen production to its own unit after all. adding more hints to the ui, and allowing the rush of kongregate newbies some time to learn the game, has helped confusion around this quite a bit. #354 will improve this further too.

a mutagen larvae nerf is becoming more urgent though:

> maybe give production a curve, rather than linear the way it is now - worried about mutagen larva being productive for too long.

this was a valid worry, I underestimated how well it scales - it's ended up carrying people for far longer than I intended, and due to how mutagen gains work it's not going to stop scaling so well without a nerf. I can live with it making the road to overminds easier than I planned ("what I planned" isn't necessarily "what's best"), but the current scaling affects/hurts future content too, and nerfing it now will hurt less than nerfing it later.

**Comment by erosson** [comment]
I want to keep territory relevant and keep mutagen's scaling issues under control, so the simplest solution is to make mutagen affect territory instead of spawning flat larvae; territory's scaling is very much under control. I also want to make territory mutation useful. current thinking:

* mutagen loses its linear larvae production. mutagen gains a (root? linear? certainly not logarithmic) bonus to all territory production - similar to territory mutations today, but scaling better.
* territory mutation loses its logarithmic territory production. adds to the twin level of all territory units (logarithmically), and also changes twins to create up to 3 creatures per level instead of 2 (asymptotically).

problem: many more expansions -> much more mutagen gained from expansions -> hatchery mutagen is irrelevant, and mutagen gains per time could actually *increase* if we get the numbers wrong (though the flat larvae nerf may slow things down enough to be okay; just need to watch for it). might need to nerf expansion mutagen to counter this - I've been considering reworking it anyway to remove/reduce the random factor from expansion mutagen to appease players who can't stand mutagen's randomness anyway (hatcheries stay random with a higher but less consistent average payout), so this could work.

problem: very advanced players hate me forever because I nerfed their larvae (and this is, without question, a nerf). oh well, that's pretty much unavoidable at this point. keeping territory relevant is too important to leave things as they are. we can avoid a lot of the flak by waiting and releasing this with other content updates, but that means more people reach the endgame before the nerf; if we release soon fewer people will be at the stage of the game where it matters. I don't want new content to feel rushed.

problem: moderately advanced players, optimally, never ascend again because they got overmind vi's under the current rules and can't get back to that point after the nerf. this could be a problem, and it'll be a problem with any larvae nerf. could force an ascension on them, but that would just piss them off more. could offer some sort of reset incentive (can't use new/buffed territory mutation without a reset?), but advanced meat units are a tough incentive to match. need to think about this one.

*****

of course, a more conservative fix is to keep mutagen as-is but change how it scales after some fixed point - early on it's linear larvae like today, after (say) 1e80 mutagen it changes and starts log-scaling or root-scaling. territory mutation changes discussed above can be done independently, though it's a bit weird to have no way to scale territory produced per unit.

**Comment by DayShine** [comment]
My immediate reaction to this is:

As far as I can tell the mutagen larvae bonus is the only thing that speeds up my early game when I ascend.

This game is already very slow, taking me 3/4 days to overtake the mutagen bonus, which means 5/6 days to reach my previous progress. At which I point I spend my mutagen and get a 10-20% bonus.

That 10-20% bonus does not increase the speed of my next run significantly by itself, so the remove of the mutagen larvae would mean my next run would probably take 8/9 days to reach.

I urge you to very carefully consider where the bonus from ascension is actually coming from, because right now, 3 ascensions in, I ascend for the mutagen larvae, not the mutagen bonuses.

**Comment by erosson** [comment]
so after running more math on mutagen->territory, my intuition was wrong - no amount of territory from mutagen will ever be enough to compare to today's mutagen bonus. mutagen today scales larvae production with no diminishing returns, or an exponent of 1. territory scales larvae with an exponent of `log(1.1)/log(2.45) = 0.1063` ; 1 more digit of larvae production takes just over 9 digits of territory; that's not *too* far off from what I actually see in-game. doesn't matter how much territory mutagen gives, 90% fewer zeros at the end of larvae production is way too painful for everyone.

let's give mutagen a simple larvae production bonus instead, multiplicative with hatcheries and expansions. "multiplicative with expansions" ensures territory stays relevant. somewhere between 0.1063 and 1 is a larvae rate we can use for mutagen that'll keep the pace of the game under control while still keeping ascension worthwhile. this removes the strategic element of spending-mutagen-later that we have today, but I don't think that's too big a loss.

*****

the changelists above this post implement this (in their own branch, not up for release until you see an announcement in the subreddit):

* remove mutagen's larvae production, replacing it with a bonus to hatchery larvae production - scales with exponent 0.4. (I'd never intended for it to be worthwhile to keep unspent mutagen around long-term, but that's how things worked out, so let's go with it)
* buff hatchery mutations, now scales with exponent 0.2 instead of log-scaled. also starts with a few extra zeros so it's better than raw mutagen early on, but dumping all mutagen into it is still suboptimal because it's multiplicative with raw mutagen
* buff territory mutations, now scales *linearly* - so territory mutation scales larvae production with exponent 0.1063
  * this one might be a problem - late-game, mutation-territory's scaling will trivialize territory gained from empowering, etc. and people could just run around with a few unupgraded swarmlings to get most of the bonus. maybe rework this to scale with empower level or creature type. or maybe leave it, giving people who've made it this far the right to slack off on upgrading their territory units... need to think this over.

all these are multiplicative, so late-game mutagen divided optimally among these will scale larvae with exponent (0.4+0.2+0.1ish) = 0.7ish after these changes, down from exponent 1 on mutagen today. early on, when hatcheries/expansions produce more larvae than mutagen for most of the game, making mutagen multiplicative with them is a solid buff; late game, where mutagen's superior scaling overwhelmed hatcheries/expansions most of the time, this is still a nerf (as intended) but a 0.7 scale factor is still worthwhile.

this is all theorycraft so far, haven't playtested at all yet.

**Comment by erosson** [comment]
closing this - I'm happy with the above plan to make mutagen affect hatchery production with diminishing returns. #488 will fiddle with the balance and numbers, but disregarding balance, things are functioning okay in the 1.1 branch.
