### ISSUE TITLE
hybrid engineering notation

### ISSUE THREAD

**Issue by erosson** [swarmsim/swarm#321]
> number format option of classic/engineering hybrid (current hybrid is only scientific) would be cool

easy to code, reasonable request, but worried about options bloat. maybe.

**Comment by Shoelace** [comment]
the obvious solution is
Standard decimal, Scientific-E , sci-Hybrid , Engineering , e-Hybrid 

but maybe it should be
standard decimal, scientific ,  engineering with a hybrid  checkbox?

of course standrad + hybrid is nonsense, so maybeth the checkbox cold be disabled for that option.

**Comment by Shoelace** [comment]
are teh any other number format options?
i dont see a point for say hexdecimal,   0x3F Billion  ?!?!  or  0xD3.3A4 E0x16  
and we shouldnt need to worry about thousand groupings and decimal markers.. the number format library should take care of international issues

**Comment by erosson** [comment]
#440 will make this possible without bloating the list of options. closing this in favor of #440.
