### ISSUE TITLE
welcome back production should show on import load

### ISSUE THREAD

**Issue by Shoelace** [swarmsim/swarm#328]
when you load/import a savegame.. it would be good if the welcome back screen showed.

example.
i saved my game from home to a text file
came to work and pasted it into the box.

i kind of expected the welcome back to tell me my production for the period of time.. (about an hour)
but it did not.

NB: this should also trigger on the dropbox savesync import also

**Comment by erosson** [comment]
this would fix some screwiness that happens if you import a game without closing the welcome-back box, too.
