### ISSUE TITLE
slider, instead of checkbox, for upgrade notifications

### ISSUE THREAD

**Issue by erosson** [swarmsim/swarm#350]
another improvement to upgrade notification usability. probably show some descriptive text below the slider, but only while the user's sliding so the ui stays clean. several settings:

* notifications off - unchecked today
* notify at 1x cost - checked today
* notify at 2x cost - efficient for "faster" upgrades
* notify at 4x cost - the "buy all cheapest upgrades" threshold

**Comment by xanthousphoenix** [comment]
A 1.5x option would also be nice, because the faster <x> upgrades are optimally bought at 1.5x the cost.

**Comment by erosson** [comment]
this worked better as a dropbown. also includes hide-upgrade, #560.

> An idea would be to have an autobuy feature,

autobuy is a much bigger change - not its implementation necessarily, but its effect on gameplay - and I'm not sure if I want that yet.
