### ISSUE TITLE
themes: darkly, paper progress bars

### ISSUE THREAD

**Issue by erosson** [swarmsim/swarm#392]
many complaints about the tiny progress bars. they do look really bad with text, though technically they're as-designed. #377

**Comment by Shoelace** [comment]
the css class .progress is controlling the height.

effectively
darkly
 .progress { height: 10px; }
paper
 .progress { height: 6px; }

most of the other themes use a height of 20px.


i dont know if you can override this.. or if you'd even want to,  it is just the theme.
