### ISSUE TITLE
dropbox not working on win 8 phone

### ISSUE THREAD

**Issue by erosson** [swarmsim/swarm#437]
https://mail.google.com/mail/u/0/#search/label%3A!swarmsim++is%3Aunread/14bd2dc732d9527b

> Hey there, I was just trying to import my save from my mobile device back onto my computer. Besides not being able to copy/paste huge amounts of text (user error) the dropbox link also just doesn't work. I'm able to sign in but all I get after that is a blank page that says "this is teh body". Otherwise it works fine on mobile
> 
> The address that gives that message is /views/dropboxauth.html
> I'm using the windows 8 phone
> 
> I don't even know what I'm going to do to retrieve the game file... I tried looking for the system files to retrieve local internet storage but system files are inaccessible on this thing. It seems to be stuck on my phone for now

**Comment by Shoelace** [comment]
"this is the body"  can be removed from /views/dropboxauth.html .. i added it to debug something..

dropbox import worked fine on ios 8.1.3 on an iphone 5s

i dont have access to any other mobiles to try.

one possible solution to this would be the 'short url' button you were considering..

**Comment by erosson** [comment]
> one possible solution to this would be the 'short url' button you were
considering..

That is a really good point I had not thought of. Thanks!

On Tue, Mar 3, 2015 at 2:14 AM, David Pyke Le Brun <notifications@github.com

**Comment by Shoelace** [comment]
If you go this way you’ll need to consider how to import a ‘short save’ also.
I assume if you paste the url into the import field.. the full length url could be retrieve and replaced inplace.?
