### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by erosson** [swarmsim/swarm#458]
would be nice

**Comment by Shoelace** [comment]
what are you thinking..  1-6 for tabs? and then per tab a-z ?  would be good to have some indication what the hotkey for an action is.

**Comment by erosson** [comment]
not sure, haven't thought about what the keys would be. would almost certainly need a separate key config screen.

> would be good to have some indication what the hotkey for an action is.

Probably underline it, or put it somewhere in light grey text, the way windows interfaces do.

**Comment by Anahkiasen** [comment]
I'd love a shortcut for "Buy all upgrades", and yeah, 1-6 for the tabs

**Comment by erosson** [comment]
related to a buy-all-upgrades shortcut: #471

**Comment by erosson** [comment]
requested keyboard shortcut for a single cast of swarmwarp, and probably other abilities - makes a lot of sense. https://www.reddit.com/r/swarmsim/comments/304bi4/endgame_experience_and_ui_suggestions/

**Comment by erosson** [comment]
starting slow, with a shortcut for undo and for selecting each tab. will likely add more later.
