### ISSUE TITLE
Energy view doesn't show decimals

### ISSUE THREAD

**Issue by vperic** [swarmsim/swarm#484]
Using the "seconds" velocity format, the energy gained (from the "overview" window for Energy) doesn't show decimals, ie. is capped at +1/s (changing velocity formats confirms that no decimals are ever shown). Since you never do get much energy, this difference can be significant -- why not show 2 decimals like everywhere else?

**Comment by erosson** [comment]
I think it used to - must've stopped at some point. This is certainly a bug. Thanks!
