### ISSUE TITLE
Unable to buy more than 1e38 of a mutation

### ISSUE THREAD

**Issue by technocoreai** [swarmsim/swarm#487]
Whenever I enter try to enter more than 1e38 in the mutation quantity field, the input field bugs out and resets to empty.

**Comment by erosson** [comment]
1e39 works fine for me - 1e300 doesn't though, maybe you're running into #281?

**Comment by technocoreai** [comment]
Seems to be browser dependent, because Safari fails at 1e38 in that jsfiddle as well.
