### ISSUE TITLE
Amount of Nexuses 

### ISSUE THREAD

**Issue by TheMrNobody** [swarmsim/swarm#507]
If you decode the save, you are able to alter amount Nexuses(Nexi?). Need to add an algorithm for checking if the amount of them is over the limit
[![wot](https://farm9.staticflickr.com/8699/16321353684_9d2f6c864a_o.png)](https://farm9.staticflickr.com/8699/16321353684_9d2f6c864a_o.png)

**Comment by Shoelace** [comment]
lol.. I think that once you start editing saves all bets are off.

i think given the small number of items that have a maximum set and teh fact you need to edit the save makes this a very low priority.. maybe even a wontfix.

**Comment by erosson** [comment]
Not going to fix this. Swarmsim code does try to make cheating nontrivial (system clock; unique save encoding), so this isn't an unreasonable idea - but once someone knows how to decode the save or edit unit counts with js it's game over anyway, they can still cheat with every other unit and we can't stop them, so why bother.

Also, I actually use large numbers of nexus when testing sometimes, so don't want to remove this everywhere. Could conditionally check it in production only, but I'd rather not add more stuff that's permanently different in prod vs. dev.

Thanks anyway!
