### ISSUE TITLE
install script seems broken (xubuntu 14.10)

### ISSUE THREAD

**Issue by zorbathut** [swarmsim/swarm#549]
I'm attempting to install Swarmsim through the documented method in https://github.com/swarmsim/swarm/blob/master/install.sh . Unfortunately, at least on a fresh Xubuntu 14.10, stuff seems broken.

First, bower is not installed; I manually fixed this with "sudo npm install -g bower". Second, bower then complained about esprima not being installed; I tried "bower install esprima", then "npm install esprima", and one of those "fixed" it . . .

. . . in the sense that I now get the following error:

/home/zorba/swarm/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33
    }).flatten().uniq().value();
       ^
TypeError: Object Gruntfile.js has no method 'flatten'
    at Object.module.exports [as findup] (/home/zorba/swarm/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33:8)
    at Task.task.init (/home/zorba/swarm/node_modules/grunt/lib/grunt/task.js:427:16)
    at Object.grunt.tasks (/home/zorba/swarm/node_modules/grunt/lib/grunt.js:120:8)
    at Object.module.exports [as cli] (/home/zorba/swarm/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Finally, it's worth noting that "sudo npm install" absolutely spams me with warnings:

npm WARN cannot run in wd swarm@1.0.47 bower install (wd=/home/zorba/swarm)
npm WARN unmet dependency /home/zorba/swarm/node_modules/karma requires lodash@'~2.4.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/lodash,
npm WARN unmet dependency which is version 3.6.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/bower/node_modules/inquirer requires chalk@'^0.5.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/bower/node_modules/chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/bower/node_modules/inquirer requires lodash@'~2.4.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/lodash,
npm WARN unmet dependency which is version 3.6.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/bower/node_modules/cardinal/node_modules/redeyed requires esprima@'~1.0.4' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/esprima,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/bower/node_modules/configstore/node_modules/js-yaml requires esprima@'~ 2.0.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/esprima,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/bower/node_modules/tar-fs/node_modules/tar-stream/node_modules/bl requires readable-stream@'~1.0.26' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt/node_modules/js-yaml requires esprima@'~ 1.0.2' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/esprima,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt/node_modules/grunt-legacy-log requires lodash@'~2.4.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt/node_modules/lodash,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-connect/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/archive-type/node_modules/meow/node_modules/indent-string requires minimist@'^1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/meow/node_modules/indent-string requires minimist@'^1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-check/node_modules/executable/node_modules/meow/node_modules/indent-string requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/semver-truncate requires semver@'^4.0.3' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/bin-version/node_modules/find-versions requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/bin-version/node_modules/find-versions requires minimist@'^1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-tar/node_modules/strip-dirs requires chalk@'^0.5.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/archive-type requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/archive-type requires meow@'^3.1.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/meow,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/decompress requires meow@'^3.0.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/meow,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/archive-type/node_modules/file-type requires meow@'^3.0.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/meow,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/download-status requires chalk@'^0.5.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/semver-truncate requires semver@'^4.0.3' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/bin-version/node_modules/find-versions requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/bin-version/node_modules/find-versions requires minimist@'^1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-tar/node_modules/strip-dirs requires chalk@'^0.5.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-tarbz2/node_modules/strip-dirs requires chalk@'^0.5.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/decompress requires meow@'^3.0.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/meow,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/archive-type/node_modules/meow/node_modules/indent-string requires minimist@'^1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/decompress/node_modules/buffer-to-vinyl/node_modules/file-type requires meow@'^3.0.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/meow,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/download-status requires chalk@'^0.5.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/executable/node_modules/meow/node_modules/indent-string requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/executable/node_modules/meow/node_modules/indent-string requires minimist@'^1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/semver-truncate requires semver@'^4.0.3' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/bin-version/node_modules/find-versions requires minimist@'^1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-tar/node_modules/strip-dirs requires chalk@'^0.5.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/logalot/node_modules/squeak requires chalk@'^0.5.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/decompress requires meow@'^3.0.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/meow,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/archive-type/node_modules/meow/node_modules/indent-string requires minimist@'^1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/decompress/node_modules/buffer-to-vinyl/node_modules/file-type requires meow@'^3.0.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/meow,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/download-status requires chalk@'^0.5.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/executable requires meow@'^3.1.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/meow,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/bin-version/node_modules/find-versions requires minimist@'^1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress-targz/node_modules/strip-dirs requires get-stdin@'^4.0.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/get-stdin,
npm WARN unmet dependency which is version 3.0.2
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/bower requires chalk@'0.5.0' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-google-cdn/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/cdnjs-cdn-data requires semver@'~2.2.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/semver,
npm WARN unmet dependency which is version 2.3.2
npm WARN unmet dependency /home/zorba/swarm/node_modules/grunt-wiredep/node_modules/wiredep requires lodash@'^2.4.1' but will load
npm WARN unmet dependency /home/zorba/swarm/node_modules/lodash,
npm WARN unmet dependency which is version 3.6.0

which may or may not be relevant.

Unfortunately I am not familiar enough with js development to troubleshoot from here.

This is on a completely vanilla Xubuntu 14.10 VM - quite literally I installed the OS and ran the install script. Please help! I'm trying to implement a minor quality-of-life UI feature :)

**Comment by erosson** [comment]
* bower was entirely missing from the install script; oops. Added it.
* googling your error pointed me to https://github.com/gruntjs/grunt/issues/888, which says swarmsim's .gitignore was too aggressive. Fixed that too. (Not sure how this one never caused trouble before.)

I think those changes will fix things for you - ran a test just now on a fresh ubuntu 14.04 ec2 machine (they didn't have an obvious 14.10 image) and things worked. Make sure you delete the swarm/ directory your first install-attempt left behind.

I don't get to test this script often, so I really appreciate the bug report; thanks a lot! Let me know if things are (or aren't) working now.

**Comment by zorbathut** [comment]
Whoops, my mistake for not googling that error.

The only remaining bit of manual intervention needed was "sudo apt-get install openjdk-7-jre". I don't know if you'd want to add that into the install script since people may want to run different Java runtimes. And that one's easy enough to do manually if you know the Linux environment at all.

Thanks for the quick turnaround!
