### ISSUE TITLE
remove dropbox storage

### ISSUE THREAD

**Issue by erosson** [swarmsim/swarm#623]
> Hi Evan,
> 
> Today we published a post on the Dropbox developer blog about deprecating the Sync and Datastore APIs:
> 
> https://blogs.dropbox.com/developers/2015/04/deprecating-the-sync-and-datastore-apis/
> 
> Your app, Swarm Simulator, currently uses the Datastore API. I also noticed that it's been growing a ton since launch, which is really awesome - congrats!
> 
> I appreciate that you've chosen to integrate Dropbox into your app, and our team wants to help in any way possible as you migrate to a different solution. Please take a look at the blog post and let me know how we can help.

https://mail.google.com/mail/u/0/#inbox/14ce8181ceb5322a

:(

though, since v1.1 will add storage on swarmsim servers and server-side accounts, we're already in a good spot for dealing with this. pretty sure we can still authenticate our accounts with dropbox, that's not deprecated - #570, #582 - we'll just be using our own storage instead.

blog says we've got until april 2016 until dropbox storage is gone - more than enough time to finish 1.1 and get everyone moved. might not actually remove this until a while after 1.1's out - give people time to start usign the new storage.

@Shoelace , just fyi

**Comment by Shoelace** [comment]
well that feels like a bit of a waste of time then..  still i've been using the dropbox sync with swarmsim since it went live..  so its certainly made my life easier for the past several weeks

c'est la vie.

**Comment by rlpowell** [comment]
So I don't know if this is related, but as of ... maybe a week ago?, the dropbox buttons just don't do anything at all.  Total non-ops.  Should I open a new bug for that?

**Comment by erosson** [comment]
Hello again swarmsim, it's been a while

Dropbox buttons haven't worked for a very long time since Dropbox killed this part of their service, yes. I've removed Dropbox from swarmsim, but added Playfab as a replacement.

> v1.1 will add storage on swarmsim servers and server-side accounts

isn't happening after all.
