### ISSUE TITLE
Grammar: pronoun "who" should be changed to "that"

### ISSUE THREAD

**Issue by IanKemp** [swarmsim/swarm#656]
The description of the Locust currently reads:

"Groups of hungry locusts devour any creature **who** makes the mistake of standing in their way."

This should probably be changed to:

"Groups of hungry locusts devour any creature **that** makes the mistake of standing in their way."

As per http://grammarist.com/usage/that-who/, "As for whether it’s okay to use who in reference to animals, this is a matter of preference. Some people think of their cats, for instance, as thinking beings with real personalities and wouldn’t hesitate to refer to them with who. The same people might not do the same for, say, a jellyfish. But most edited publications use that and which in reference to animals."

In this circumstance, the creature(s) being devoured by the Locust can be anything, from humans to animals to micro-organisms, so "that" is a more appropriate pronoun.

**Comment by erosson** [comment]
Good catch, thanks! I appreciate the citation, made the mistake easier to check. This should be fixed in the next release.
