### ISSUE TITLE
publictest branch

### ISSUE THREAD

**Issue by erosson** [swarmsim/swarm#660]
feature flags are getting awkward, and saved data changes are dangerous to push to production. we'll need this eventually for versioning anyway.

**Comment by erosson** [comment]
the commits above: 

* create a `1.1-master` branch for v1.1 changes.
* disable production deployments in the new 1.1 branch.
* set sensible defaults for `grunt serve` and v1.1, previously done via --flags.
* creates a new chagnelog section.
* rollback most changes to the `master`/production branch, except for those I cherry-picked as safe. this ensures production's safe to push.
* rollback the above rollback in the `1.1-master`/publictest branch. nothing's changed here, but the double-rollback allows clean merging/rebasing.

no publictest branch for the server - it's much simpler than the client.

**Comment by Shoelace** [comment]
@erosson do you have a public test running yet?
i havent tried building/running locally since you created the server and stuff..  but i'm curious how all these new features are coming along..

**Comment by Shoelace** [comment]
Yeah cool

I got my own copy running yesterday anyway. There appears to be lots of missing npm dependencies but it worked. I had to disable a bunch of authorizing stuff as I didn't have app keys etc. I'll give some more feedback Monday.
