### ISSUE TITLE
[IDEA] Desktop Notifications

### ISSUE THREAD

**Issue by AlphaT3ch** [swarmsim/swarm#668]
I've noticed browsers like [Chrome](https://developer.chrome.com/extensions/notifications) and [Safari](https://developer.apple.com/notifications/safari-push-notifications/) now support desktop notifications while having the website active in the background. Could the game possibly notify you when you have an upgrade available? Since it also works while actually having the site open, you could just replace the blue bubble/cloud notification with this. I also found out that [Ubuntu](https://wiki.ubuntu.com/NotifyOSD) has a desktop notification system too! If this could be added, I would truly appreciate it! Thank you!

Also, this would only work while the game is open, not 24/7.

**Comment by erosson** [comment]
Excellent idea - see #441. :) Thanks for the extra documentation links; they'll help when I find time for this!
