### ISSUE TITLE
Height problems on Chrome

### ISSUE THREAD

**Issue by rlpowell** [swarmsim/swarm#684]
On both Android and Windows in Chrome, the height of the sub-window in which all the items exist isn't high enough.  Things keep getting clipped.

https://www.dropbox.com/s/0c3ktj3e4ml8i3v/Screenshot%202016-05-07%2019.31.25.png?dl=0

See that mini-scrollbar on the right?  Yeah, that's obnoxious.  Can you make that frame or whatever taller?

**Comment by erosson** [comment]
A bit late, but this should be fixed
