### ISSUE TITLE
Resetted cookies, big problems.

### ISSUE THREAD

**Issue by AugiteSoul** [swarmsim/swarm#687]
Because of another site I had to reset my cookies (I use Firefox btw) and it shows only the game's title and those two things: v{{version}}
{{onRender()}}
Could you see what is the problem and fix it? Thanks.

**Comment by Shoelace** [comment]
unless you have saved your progress seperately to a file or play via kongregate you are probably out of luck and have lost your game and would need to start again.

as for seeing {{version}} etc  a reload (or shift-reload) should fix that.
