### ISSUE TITLE
Crashes in Chrome 53.0.2785.116 (64-bit)

### ISSUE THREAD

**Issue by Mrtenz** [swarmsim/swarm#689]
The tab crashes after about 5 minutes.

**Comment by erosson** [comment]
Cannot reproduce the crash, mine happily ran for half an hour or so just now. Using `Version 53.0.2785.116 m (64-bit)`

Realistically, I'm just not going to be able to deeply investigate this anytime soon. I'm sorry.

**Comment by Afrandsen87** [comment]
I have the same issue currently. Chrome 54.0.2840.71 . The tab dies, and alternates between saying it ran out of memory, or saying the process was killed. I can see in the process explorer that it keeps eating memory gradually.

**Comment by duartecordeiro** [comment]
Version 54.0.2840.99 m (64-bit)
Crashes every 5 or 10 min with an "out of memory error".

**Comment by MitchRuns** [comment]
I'm also having this issue in 54.0.2840.99 m (64-bit) where it crashes with a memory error.

**Comment by erosson** [comment]
If swarmsim.github.io still crashes for you, could you try out https://beta.swarmsim.com/#/ ? Thanks!

I'm still unable to reproduce these crashes. The beta site updates all of swarmsim's dependencies - there's a lot of them, and a year and a half is a lot of time to get out of date, so if one of them is the source of the crash this might fix it.

If the beta site still crashes for you, please send me your saved game and I'll try again. Thanks!

https://www.reddit.com/r/swarmsim/comments/5mjj5n/testing_v1060_online_saves_work_again/

**Comment by erosson** [comment]
> I can see in the process explorer that it keeps eating memory gradually.

Do you mean chrome's task manager - shift + esc? That's not necessarily bad. It's normal for swarmsim's memory to gradually climb, then drop sharply when garbage collection kicks in; that cycle repeats.

**Comment by erosson** [comment]
No recent complaints of this one, and there's [one report that this is fixed](https://www.reddit.com/r/swarmsim/comments/5fjkem/anyone_else_get_this_screen_every_minute_or_so/dcacy9h/?st=iydjzp3r&sh=200bfd3e), so I think this is better now.
