### ISSUE TITLE
Icon doesn't work

### ISSUE THREAD

**Issue by Allen-B1** [swarmsim/swarm#711]
When I press "add to home screen", it just shows a gray "S" (the default if there isn't any icon). I think you need a 144x144 icon. https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/

**Comment by erosson** [comment]
I've seen the same thing. `manifest.json` has a 144x144 icon though, so I'm not quite sure what's going on.

https://github.com/swarmsim/swarm/blob/master/app/manifest.json#L22  
https://github.com/swarmsim/swarm/blob/master/app/apple-touch-icon-144x144-precomposed.png

[Lighthouse](https://developers.google.com/web/tools/lighthouse/) seems to think the icon is okay, though neither of us are actually observing that. Haven't yet had time to investigate this further.

**Comment by Allen-B1** [comment]
Well on this article https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/
On the first example, it has `48x48`, `96x96`, and `192x192` and as of today you have none of them
On the second example, it has `128x128`, `152x152`, `144x144`, and `192x192` and you only have `144x144` and `152x152` so maybe you should to `192x192` since it's in both of them

**Comment by erosson** [comment]
Adding a bunch more icon sizes, plus changing the type from "png" to "image/png", seems to have done the trick. (Neither did the trick alone (or if it did, I messed up somewhere and missed it))

I read a few of the help pages on that site, but missed that one. Thanks!

Unrelated question: you've made a few swarmsim contributions so far; thanks! [I'm working on a sequel](https://news.warswarms.com/announcing-war-swarms/). (I'll announce it on the subreddit a little later tonight.) Invite-only beta should start sometime this month. When it does, would you like an invite?
