### ISSUE TITLE
install.sh fails on Ubuntu 17.10

### ISSUE THREAD

**Issue by gerbilOFdoom** [swarmsim/swarm#713]
In Ubuntu 17.10 the apt package nodejs-legacy is no longer available because it is, as best I can tell, now included in the standard nodejs package. As a result the install script fails to run properly.

My fix was to remove nodejs-legacy from install.sh but that solution isn't quite enough for a pull request.

**Comment by erosson** [comment]
Verified, thanks for the report.

up-to-date node install process: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
